Allow overlaps to avoid plotting problems
Graphviz builds on CentOS 7 miss an external library, so this message is
printed when using overlap=false:

> Error: remove_overlap: Graphviz not built with triangulation library

In many cases, the graph is then also not plotted.